// Generated by CoffeeScript 2.3.2
(function() {
  var Canvas;

  Canvas = new Layer({
    width: 1440 / 2 - 100,
    height: 2960 / 2 - 100,
    x: Align.center(),
    y: Align.center()
  });

}).call(this);
