// Generated by CoffeeScript 2.3.2
(function() {
  var Border, canvasBorder, phoneCanvas;

  phoneCanvas = new Layer({
    width: 1440 - 10,
    height: 2960 - 10,
    x: Align.center(),
    y: Align.center()
  });

  canvasBorder = new Border;

  Border = class Border extends Layer {
    constructor(options) {
      super(options);
      this.left = new Layer({
        x: Align.left(),
        y: 0,
        width: 10,
        height: phoneCanvas.height
      });
      this.right = new Layer({
        x: Align.right(),
        y: 0,
        width: 10,
        height: phoneCanvas.height
      });
      this.top = new Layer({
        x: 0,
        y: Align.top(),
        width: phoneCanvas.width,
        height: 10
      });
      this.bottom = new Layer({
        x: 0,
        y: Align.bottom(),
        width: phoneCanvas.width,
        height: 10
      });
    }

  };

}).call(this);
