// Generated by CoffeeScript 2.3.2
(function() {
  var Border, canvasBorder, phoneCanvas, phoneScreen;

  phoneScreen = new Layer({
    width: 1440,
    height: 2960,
    x: Align.center(),
    y: Align.center(),
    backgroundColor: "transparent"
  });

  phoneCanvas = new Layer({
    parent: phoneScreen,
    width: 1440 - 10,
    height: 2960 - 10,
    x: Align.center(),
    y: Align.center()
  });

  Border = class Border extends Layer {
    constructor(options = {}) {
      super(_.defaults(options, {
        backgroundColor: "transparent"
      }));
      this.size = this.parent.size;
      this.left = new Layer({
        parent: this,
        x: Align.left(),
        y: Align.center(),
        width: 10,
        height: this.height,
        backgroundColor: "red"
      });
      this.right = new Layer({
        parent: this,
        x: Align.right(),
        y: Align.center(),
        width: 10,
        height: this.height,
        backgroundColor: "red"
      });
      this.top = new Layer({
        parent: this,
        x: Align.center(),
        y: Align.top(),
        width: this.width,
        height: 10,
        backgroundColor: "red"
      });
      this.bottom = new Layer({
        parent: this,
        x: Align.center(),
        y: Align.bottom(),
        width: this.width,
        height: 10,
        backgroundColor: "red"
      });
    }

  };

  canvasBorder = new Border({
    parent: phoneScreen
  });

}).call(this);
